# Generated by Django 3.1.5 on 2021-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210125_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bshop',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
